spring:
  security:
    user:
      name: moabbas
      password: Mm11111!
  application:
    name: ChatStack
  datasource:
    url: jdbc:postgresql://bml420vp4oyqyn1eaefe-postgresql.services.clever-cloud.com:50013/bml420vp4oyqyn1eaefe
    username: ubqydpf1s713gzngzeyu
    password: XoORg6NZeYOu9ASrIm9zwMXBRZWFS9
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: mohammadabbassa33@gmail.com
    password: oyxobuzgjqtlewnq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  base-url: http://localhost:8080/


#  POSTGRESQL_ADDON_HOST=bml420vp4oyqyn1eaefe-postgresql.services.clever-cloud.com
#  POSTGRESQL_ADDON_DB=bml420vp4oyqyn1eaefe
#  POSTGRESQL_ADDON_USER=ubqydpf1s713gzngzeyu
#  POSTGRESQL_ADDON_PORT=50013
#  POSTGRESQL_ADDON_PASSWORD=XoORg6NZeYOu9ASrIm9zwMXBRZWFS9
#  POSTGRESQL_ADDON_URI=postgresql://ubqydpf1s713gzngzeyu:XoORg6NZeYOu9ASrIm9zwMXBRZWFS9@bml420vp4oyqyn1eaefe-postgresql.services.clever-cloud.com:5432/bml420vp4oyqyn1eaefe

#  @Mapper(componentModel = "spring")
#  public interface UserMapper {
#  UserDto toDto(User user);
#  User toEntity(UserDto dto);
#}
